@startuml
!include ./article/includes/style.iuml

hide footbox
actor UserA
participant Node1
participant Node2
actor UserB

UserA -> Node1: Шлет сообщение UserB
Node1 -> Node2: Пересылка нужной ноде
Node2 -> UserB: Отправка конечному пользователю


@enduml