@startuml
!include ./article/includes/style.iuml

hide footbox
actor UserA
participant Node1
collections Redis
participant Node2
actor UserB

UserA -> Node1: Шлет сообщение UserB
Node1 -> Redis: Пересылка в редис
Redis -> Node2: Пересылка нужной ноде
Node2 -> UserB: Отправка конечному пользователю


@enduml